version: "3.3"

volumes:
  ftp_data:

services:
  ftp:
    image: delfer/alpine-ftp-server
    networks:
      - default
    volumes:
      - ftp_data:/home/vsftpd
    environment:
      - USERS=myuser|mypass@1234
      - ADDRESS=127.0.0.1
      - MIN_PORT=21000
      - MAX_PORT=21010
    ports:
      - 20-21:20-21
      - 21000-21010:21000-21010
    restart: always