version: "3.3"

volumes:
  ftp_data:

services:
  ftp:
    image: dotkevinwong/vsftpd-arm
    volumes:
      - ftp_data:/home/vsftpd
    environment:
      - FTP_USER=myuser
      - FTP_PASS=mypass@1234
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    ports:
      - 20-21:20-21
      - 21100-21110:21100-21110
    restart: always