version: "3.3"

volumes:
  ftp_data:

services:
  ftp:
    image: stilliard/pure-ftpd:hardened
    volumes:
      - ftp_data:/home/ftpusers
    environment:
      - FTP_USER_NAME=myuser
      - FTP_USER_PASS=mypass@1234
      - PUBLICHOST=127.0.0.1
      - FTP_PASSIVE_PORTS=21000:21010
    ports:
      - 20-21:20-21
      - 21000-21010:21000-21010
    restart: always