version: "3.3"

volumes:
  ftp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/ftp_data'

services:
  ftp:
    image: delfer/alpine-ftp-server
    networks:
      - default
    volumes:
      - ftp_data:/home/vsftpd
    environment:
      - USERS="myuser|mypass"
      - ADDRESS=127.0.0.1
      - MIN_PORT=21000
      - MAX_PORT=21010
    ports:
      - 20-21:20-21
      - 21000-21010:21000-21010
    restart: always

#docker run -d -p 20:20 -p 21:21 -p 21100-21110:21100-21110 -e FTP_USER=myuser -e FTP_PASS=mypass -e PASV_ADDRESS=127.0.0.1 -e PASV_MIN_PORT=21100 -e PASV_MAX_PORT=21110 --name vsftpd --restart=always fauria/vsftpd
