version: "3.3"

volumes:
  ftp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/ftp_data'

services:
  ftp:
    image: fauria/vsftpd
    networks:
      - default
    volumes:
      - ftp_data:/home/vsftpd
    environment:
      - FTP_USER=myuser
      - FTP_PASS=mypass
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    ports:
      - 20-21:20-21
      - 21100-21110:21100-21110
    restart: always

#docker run -d -p 20:20 -p 21:21 -p 21100-21110:21100-21110 -e FTP_USER=myuser -e FTP_PASS=mypass -e PASV_ADDRESS=127.0.0.1 -e PASV_MIN_PORT=21100 -e PASV_MAX_PORT=21110 --name vsftpd --restart=always fauria/vsftpd
